fix: Channels never close when a user leaves server
typescript-community/community-bot pull request #99
Opened 2020-10-17 17:40 UTC by Gerrit0

As titled

2020-10-17 17:43 UTC, robertt commented
Thanks!

2020-10-17 17:43 UTC, robertt approved these changes

2020-10-18 12:05 UTC, ronthecookie requested changes

2020-10-20 18:30 UTC, ronthecookie approved these changes
Partially tested it but no time to test fully ATM.

2020-10-20 18:31 UTC, merged